Repository alrick19/SummitRush, pull requests merged in 2025-03, with the labels that each got.

#22 Respawn and hazards
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/RespawnPoint.prefab
  Assets/Prefabs/RespawnPoint.prefab.meta
  Assets/Prefabs/Spikes.prefab
  Assets/Prefabs/Spikes.prefab.meta
  Assets/Scenes/Level1.unity
  Assets/Scripts/CameraRoomManager.cs
  Assets/Scripts/KillPlayer.cs
  Assets/Scripts/KillPlayer.cs.meta
  Assets/Scripts/Player.cs
Labels: Gameplay Mechanics

#26 Wall mechanic
  Assets/Scripts/InputManager.cs
  Assets/Scripts/Player.cs
Labels: Gameplay Mechanics

#27 level 2 started, basic patrol enemies created and implemented
  Assets/Animations.meta
  Assets/Animations/Enemy.meta
  Assets/Animations/Enemy/Enemy.controller
  Assets/Animations/Enemy/Enemy.controller.meta
  Assets/Prefabs/Enemy.prefab
  Assets/Prefabs/Enemy.prefab.meta
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level2.unity.meta
  Assets/Scripts/EnemyController.cs
  Assets/Scripts/EnemyController.cs.meta
Labels: Gameplay Mechanics, Level Design

#30 Shadow Doppelganger
  Assets/Resources.meta
  Assets/Resources/ButtonHandler.prefab
  Assets/Resources/ButtonHandler.prefab.meta
  Assets/Resources/Enemy.prefab
  Assets/Resources/Enemy.prefab.meta
  Assets/Resources/PatrolEnemy.prefab
  Assets/Resources/PatrolEnemy.prefab.meta
  Assets/Resources/Player.prefab
  Assets/Resources/Player.prefab.meta
  Assets/Resources/RespawnPoint.prefab
  Assets/Resources/RespawnPoint.prefab.meta
  Assets/Resources/RoomTrigger.prefab
  Assets/Resources/RoomTrigger.prefab.meta
  Assets/Resources/ShadowDoppelganger.prefab
  Assets/Resources/ShadowDoppelganger.prefab.meta
  Assets/Resources/Spikes.prefab
  Assets/Resources/Spikes.prefab.meta
  Assets/Scenes/Level2.unity
  Assets/Scripts/KillPlayer.cs
  Assets/Scripts/Player/Collision.cs
  Assets/Scripts/PlayerMovementTracker.cs
  Assets/Scripts/PlayerMovementTracker.cs.meta
  Assets/Scripts/RoomTrigger.cs
  Assets/Scripts/RoomTrigger.cs.meta
  Assets/Scripts/ShadowDoppelganger.cs
  Assets/Scripts/ShadowDoppelganger.cs.meta
  ProjectSettings/TagManager.asset
Labels: Gameplay Mechanics

#36 Cutscene and more enemy designs and animations
  Assets/Fonts.meta
  Assets/Fonts/Dialog.ttf
  Assets/Fonts/Dialog.ttf.meta
  Assets/Resources/CutSceneDoppelganger.prefab
  Assets/Resources/CutSceneDoppelganger.prefab.meta
  Assets/Resources/Cutscene.prefab
  Assets/Resources/Cutscene.prefab.meta
  Assets/Resources/Enemy.prefab
  Assets/Scenes/Level1.unity
  Assets/Scripts/UI/CutsceneManager.cs
  Assets/Scripts/UI/CutsceneManager.cs.meta
  Assets/Scripts/UI/CutsceneTrigger.cs
  Assets/Scripts/UI/CutsceneTrigger.cs.meta
  Assets/Sprites/Elements/CutSceneDoppelganger.aseprite
  Assets/Sprites/Elements/CutSceneDoppelganger.aseprite.meta
  Assets/Sprites/Elements/DialogBox.aseprite
  Assets/Sprites/Elements/DialogBox.aseprite.meta
  Assets/Sprites/Enemy/Doppelganger.aseprite
  Assets/Sprites/Enemy/Doppelganger.aseprite.meta
  Assets/Sprites/Enemy/patrol-enemy1.aseprite
  Assets/Sprites/Enemy/patrol-enemy1.aseprite.meta
  Assets/Sprites/Enemy/patrol-enemy2.aseprite
  Assets/Sprites/Enemy/patrol-enemy2.aseprite.meta
  Assets/Sprites/Player/DeathAnimation.aseprite
  Assets/Sprites/Player/DeathAnimation.aseprite.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/Dialog SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/Dialog SDF.asset.meta
Labels: Visuals, UI & UX

#43 Doppelganger improved
  Assets/Animations/Doppelganger.meta
  Assets/Animations/Doppelganger/DoppelgangerController.controller
  Assets/Animations/Doppelganger/DoppelgangerController.controller.meta
  Assets/Animations/Doppelganger/Jump.anim
  Assets/Animations/Doppelganger/Jump.anim.meta
  Assets/Animations/Doppelganger/Run.anim
  Assets/Animations/Doppelganger/Run.anim.meta
  Assets/Animations/Doppelganger/dash.anim
  Assets/Animations/Doppelganger/dash.anim.meta
  Assets/Animations/Doppelganger/idle.anim
  Assets/Animations/Doppelganger/idle.anim.meta
  Assets/Animations/Doppelganger/startFall.anim
  Assets/Animations/Doppelganger/startFall.anim.meta
  Assets/Animations/Player/Climb.anim
  Assets/Animations/Player/Fall.anim
  Assets/Animations/Player/WallGrab.anim
  Assets/Resources/CutSceneDoppelganger.prefab
  Assets/Resources/DashTrail.prefab
  Assets/Resources/Particles/DoppelgangerDashParticles.prefab
  Assets/Resources/Particles/DoppelgangerDashParticles.prefab.meta
  Assets/Resources/Player.prefab
  Assets/Resources/ShadowDoppelganger.prefab
  Assets/Resources/ShadowDoppelganger.prefab.meta
  Assets/Resources/Trail1.prefab
  Assets/Resources/Trail1.prefab.meta
  Assets/Scenes/Level1.unity
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level3.unity
  Assets/Scenes/Level4.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/AnimationScript.cs
  Assets/Scripts/BaseAnimationScript.cs
  Assets/Scripts/BaseAnimationScript.cs.meta
  Assets/Scripts/Hazards/KillPlayer.cs
  Assets/Scripts/Player/DashTrail.cs
  Assets/Scripts/Player/Player.cs
  Assets/Scripts/PlayerMovementTracker.cs
  Assets/Scripts/ShadowAnimationScript.cs
  Assets/Scripts/ShadowAnimationScript.cs.meta
  Assets/Scripts/ShadowDoppelganger.cs
  Assets/Sprites/Doppelganger.meta
  Assets/Sprites/Doppelganger/CutSceneDoppelganger.aseprite
  Assets/Sprites/Doppelganger/CutSceneDoppelganger.aseprite.meta
  Assets/Sprites/Doppelganger/shadow-dash.png
  Assets/Sprites/Doppelganger/shadow-dash.png.meta
  Assets/Sprites/Doppelganger/shadow-fall.png
  Assets/Sprites/Doppelganger/shadow-fall.png.meta
  Assets/Sprites/Doppelganger/shadow-grab.png
  Assets/Sprites/Doppelganger/shadow-grab.png.meta
  Assets/Sprites/Doppelganger/shadow-idle.png
  Assets/Sprites/Doppelganger/shadow-idle.png.meta
  Assets/Sprites/Doppelganger/shadow-jumingp.png
  Assets/Sprites/Doppelganger/shadow-jumingp.png.meta
  Assets/Sprites/Doppelganger/shadow-running.png
  Assets/Sprites/Doppelganger/shadow-running.png.meta
  Assets/Sprites/Doppelganger/shadow-startfall.png
  Assets/Sprites/Doppelganger/shadow-startfall.png.meta
Labels: Visuals, UI & UX

#44 Respawn bug fix, decoupled respawning points to a level manager.
  Assets/Resources/CutsceneManager.prefab
  Assets/Resources/CutsceneManager.prefab.meta
  Assets/Scenes/Level1.unity
  Assets/Scenes/Level2.unity
  Assets/Scenes/Level3.unity
  Assets/Scenes/Level4.unity
  Assets/Scripts/Hazards/KillPlayer.cs
  Assets/Scripts/LevelManager.cs
  Assets/Scripts/LevelManager.cs.meta
  Assets/Scripts/RoomTrigger.cs
  Assets/Scripts/UI/CutsceneManager.cs
  Assets/Scripts/UI/CutsceneTrigger.cs
  ProjectSettings/TagManager.asset
Labels: Project Structure, Bug Fix

#50 Level3 finish
  Assets/Scenes/Level3.unity
  Assets/Sprites/Elements/SpiritOrb.aseprite
Labels: Level Design, Visuals
